name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install LangChain dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r langchain/requirements.txt

    - name: Install LangGraph dependencies
      run: |
        pip install -r langgraph/requirements.txt

    - name: Test LangChain imports
      run: |
        cd langchain
        python test_setup.py

    - name: Test LangGraph imports
      run: |
        cd langgraph
        python test_setup.py

    - name: Test overall dependencies
      run: |
        python test_dependencies.py

    - name: Run CI-specific tests
      run: |
        python ci_test.py

    - name: Validate example files
      run: |
        python validate_examples.py

    - name: Lint with flake8 (optional)
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

  validate-syntax:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check Python syntax
      run: |
        python -m py_compile langchain/*.py
        python -m py_compile langgraph/*.py
        python -m py_compile test_dependencies.py

  docs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check README files exist
      run: |
        test -f README.md
        test -f langchain/README.md
        test -f langgraph/README.md

    - name: Check requirements files exist
      run: |
        test -f langchain/requirements.txt
        test -f langgraph/requirements.txt
